### ISSUE TITLE
knowledge graph

### ISSUE THREAD

**Issue by kdutia** [TheScienceMuseum/heritage-connector#34]

**Comment by jamieu** [comment]
### First pass on DataStore 

## Completed

- Defined initial Elastic Search / JSON-LD structure
- Created module to load and update JSON-LD Graph and ES storage/retrieval
- Create initial SMG loader class to load objects, people and maker/user relationships 

## Comments 

- [ ] How to hold 'certainty' or 'validated' on a relationships, ?query=string (on the predicate) is a possible solution, although would need to add/remove them when storing/retrieving from ES otherwise they will appear as separate verbs/predicates when used by a RDFLib.
- [ ] Currently not using the URl/URL (of the page) as the ElasticSearch ID. Lots of good arguments for changing it so that it is (my only concern is that the URL then is then key ie. down to the https vs http at the start of the URI)
- [ ] Need a good RDF term for user/used relationships (we hold all kinds of non-maker relationships under 'user')
- [ ] There's a bunch of other relationships we could add/still need to add (but for now I have concentrated on the ones were using to keep things simple. ie. just Scheme.org FOAF and OWL ontologies for now.
- [ ] We need to filter birth/death dates before storing them
- [ ] Update loaded to work off mapping configs

## Still to do

- [ ] Mapping/transform between ES records and main HC code (ES -> Panadas)
- [ ] Mapping/transform between Wikidata and standard RDF ontologies
- [ ] Utility functions to allow additional 'facts' (triples) to be added when discovered
- [ ] Utility functions to allow reduce and map RDF triples to each other
- [ ] Utility functions to pul back subsets of data ie. type, collection, reconciled (or not), linked/unlinked etc.
- [ ] Load and support other SMG data sources ie. AdLib (documents) and Blog posts/articles (articles)
- [ ] Load and support alternative data sets / collections ie. V&A 
- [ ] Setup a Triple Store/Graph DB and sync ES (JSON-LD) data with it

**Comment by jamieu** [comment]
Wondering if N-QUADS are the the solution to our 'how do we add weights/confidence?" question.

- https://www.w3.org/TR/rdf11-primer/#section-n-quads
- https://www.w3.org/TR/n-quads/
- https://stackoverflow.com/questions/48275500/is-there-a-way-to-convert-json-ld-to-n-quads-format
- https://rdflib.readthedocs.io/en/stable/_modules/rdflib/plugins/parsers/nquads.html
